### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wannaphong** [wannaphongcom/thaipy#1]
- [x] เพิ่มเงื่อนไขใน re ไม่ให้แทนที่ sub ผิด
- [ ] เอกสาร
- [ ] ระบบติดตั้ง setup.py
- [ ] เพิ่มโมดูลให้รองรับ
- [ ] เพิ่มคำสั่ง sum และ อื่น ๆ
- [ ] อัพขึ้น pip
- [ ] Build exe in Windows
